BEGIN {
S["am__EXEEXT_FALSE"]="#"
S["am__EXEEXT_TRUE"]=""
S["LTLIBOBJS"]=""
S["LIBOBJS"]=""
S["PACKAGE_RDNS"]="org.chocolate_doom"
S["PACKAGE_MAINTAINER"]="Simon Howard"
S["PACKAGE_LICENSE"]="GNU General Public License, version 2"
S["PACKAGE_COPYRIGHT"]="Copyright (C) 1993-2025"
S["PACKAGE_SHORTDESC"]="Conservative source port"
S["PACKAGE_SHORTNAME"]="Chocolate"
S["ac_aux_dir"]="./autotools/"
S["EM_LDFLAGS"]=""
S["WINDOWS_RC_VERSION"]="3, 1, 1, 0"
S["PROGRAM_SPREFIX"]="chocolate"
S["PROGRAM_PREFIX"]="chocolate-"
S["am__xargs_n"]="xargs -n"
S["am__rm_f_notfound"]=""
S["AM_BACKSLASH"]="\\"
S["AM_DEFAULT_VERBOSITY"]="0"
S["AM_DEFAULT_V"]="$(AM_DEFAULT_VERBOSITY)"
S["AM_V"]="$(V)"
S["CSCOPE"]="cscope"
S["ETAGS"]="etags"
S["CTAGS"]="ctags"
S["am__fastdepCC_FALSE"]=""
S["am__fastdepCC_TRUE"]="#"
S["CCDEPMODE"]="depmode=none"
S["am__nodep"]=""
S["AMDEPBACKSLASH"]=""
S["AMDEP_FALSE"]=""
S["AMDEP_TRUE"]="#"
S["am__include"]="include"
S["DEPDIR"]=".deps"
S["am__untar"]="tar -xf -"
S["am__tar"]="tar --format=ustar -chf - \"$$tardir\""
S["AMTAR"]="$${TAR-tar}"
S["am__leading_dot"]="."
S["SET_MAKE"]=""
S["AWK"]="gawk"
S["mkdir_p"]="$(MKDIR_P)"
S["MKDIR_P"]="/usr/bin/mkdir -p"
S["INSTALL_STRIP_PROGRAM"]="$(install_sh) -c -s"
S["install_sh"]="${SHELL} /f/DOOM_Cosine_Chaos/chocolate-doom/autotools/install-sh"
S["MAKEINFO"]="${SHELL} '/f/DOOM_Cosine_Chaos/chocolate-doom/autotools/missing' makeinfo"
S["AUTOHEADER"]="${SHELL} '/f/DOOM_Cosine_Chaos/chocolate-doom/autotools/missing' autoheader"
S["AUTOMAKE"]="${SHELL} '/f/DOOM_Cosine_Chaos/chocolate-doom/autotools/missing' automake-1.18"
S["AUTOCONF"]="${SHELL} '/f/DOOM_Cosine_Chaos/chocolate-doom/autotools/missing' autoconf"
S["ACLOCAL"]="${SHELL} '/f/DOOM_Cosine_Chaos/chocolate-doom/autotools/missing' aclocal-1.18"
S["VERSION"]="3.1.1"
S["PACKAGE"]="chocolate-doom"
S["CYGPATH_W"]="cygpath -w"
S["am__isrc"]=""
S["INSTALL_DATA"]="${INSTALL} -m 644"
S["INSTALL_SCRIPT"]="${INSTALL}"
S["INSTALL_PROGRAM"]="${INSTALL}"
S["HAVE_ZPOOL_FALSE"]="#"
S["HAVE_ZPOOL_TRUE"]=""
S["HAVE_ICONS_FALSE"]="#"
S["HAVE_ICONS_TRUE"]=""
S["HAVE_FONTS_FALSE"]="#"
S["HAVE_FONTS_TRUE"]=""
S["HAVE_DOC_FALSE"]="#"
S["HAVE_DOC_TRUE"]=""
S["HAVE_BASH_COMPLETION_FALSE"]="#"
S["HAVE_BASH_COMPLETION_TRUE"]=""
S["HAVE_WINDRES_FALSE"]="#"
S["HAVE_WINDRES_TRUE"]=""
S["STRIP"]="strip"
S["OBJDUMP"]="objdump"
S["WINDRES"]="windres"
S["FLUIDSYNTH_LIBS"]="-lfluidsynth-3"
S["FLUIDSYNTH_CFLAGS"]="-I/mingw64/include/opus -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include"
S["PNG_LIBS"]="-lpng16"
S["PNG_CFLAGS"]="-I/mingw64/include/libpng16"
S["SAMPLERATE_LIBS"]=""
S["SAMPLERATE_CFLAGS"]=""
S["SDLNET_LIBS"]="-lSDL2_net -lmingw32 -mwindows -lSDL2main -lSDL2"
S["SDLNET_CFLAGS"]="-I/mingw64/include/SDL2 -Dmain=SDL_main"
S["SDLMIXER_LIBS"]="-lSDL2_mixer -lmingw32 -mwindows -lSDL2main -lSDL2"
S["SDLMIXER_CFLAGS"]="-I/mingw64/include/SDL2 -Dmain=SDL_main -I/mingw64/include/opus"
S["SDL_LIBS"]="-lmingw32 -mwindows -lSDL2main -lSDL2"
S["SDL_CFLAGS"]="-I/mingw64/include/SDL2 -Dmain=SDL_main"
S["PKG_CONFIG_LIBDIR"]=""
S["PKG_CONFIG_PATH"]="/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig"
S["PKG_CONFIG"]="/usr/bin/pkg-config"
S["TARGET_OS"]="x64"
S["target_os"]="mingw32"
S["target_vendor"]="w64"
S["target_cpu"]="x86_64"
S["target"]="x86_64-w64-mingw32"
S["HAVE_PYTHON"]="true"
S["RANLIB"]="ranlib"
S["OBJEXT"]="o"
S["EXEEXT"]=".exe"
S["ac_ct_CC"]="gcc"
S["CPPFLAGS"]=""
S["LDFLAGS"]=" -lmingw32 -mwindows -lSDL2main -lSDL2  -lpng16 -lfluidsynth-3 -lwinmm -lshlwapi"
S["CFLAGS"]="-O2 -g -Wall -Wdeclaration-after-statement -Wredundant-decls  -I/mingw64/include/SDL2 -Dmain=SDL_main  -I/mingw64/include/libpng16 -I/mingw64/includ"\
"e/opus -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include"
S["CC"]="gcc"
S["ac_ct_AR"]="ar"
S["AR"]="ar"
S["host_os"]="mingw32"
S["host_vendor"]="w64"
S["host_cpu"]="x86_64"
S["host"]="x86_64-w64-mingw32"
S["build_os"]="mingw32"
S["build_vendor"]="w64"
S["build_cpu"]="x86_64"
S["build"]="x86_64-w64-mingw32"
S["target_alias"]=""
S["host_alias"]=""
S["build_alias"]="x86_64-w64-mingw32"
S["LIBS"]="-lm "
S["ECHO_T"]=""
S["ECHO_N"]="-n"
S["ECHO_C"]=""
S["DEFS"]="-DHAVE_CONFIG_H"
S["mandir"]="${datarootdir}/man"
S["localedir"]="${datarootdir}/locale"
S["libdir"]="${exec_prefix}/lib"
S["psdir"]="${docdir}"
S["pdfdir"]="${docdir}"
S["dvidir"]="${docdir}"
S["htmldir"]="${docdir}"
S["infodir"]="${datarootdir}/info"
S["docdir"]="${datarootdir}/doc/${PACKAGE_TARNAME}"
S["oldincludedir"]="/usr/include"
S["includedir"]="${prefix}/include"
S["runstatedir"]="${localstatedir}/run"
S["localstatedir"]="${prefix}/var"
S["sharedstatedir"]="${prefix}/com"
S["sysconfdir"]="${prefix}/etc"
S["datadir"]="${datarootdir}"
S["datarootdir"]="${prefix}/share"
S["libexecdir"]="${exec_prefix}/libexec"
S["sbindir"]="${exec_prefix}/sbin"
S["bindir"]="${exec_prefix}/bin"
S["program_transform_name"]="s,x,x,"
S["prefix"]="/mingw64"
S["exec_prefix"]="${prefix}"
S["PACKAGE_URL"]="https://www.chocolate-doom.org/"
S["PACKAGE_BUGREPORT"]="https://github.com/chocolate-doom/chocolate-doom/issues"
S["PACKAGE_STRING"]="Chocolate Doom 3.1.1"
S["PACKAGE_VERSION"]="3.1.1"
S["PACKAGE_TARNAME"]="chocolate-doom"
S["PACKAGE_NAME"]="Chocolate Doom"
S["PATH_SEPARATOR"]=":"
S["SHELL"]="/bin/sh"
S["am__quote"]=""
  for (key in S) S_is_set[key] = 1
  FS = ""

}
{
  line = $ 0
  nfields = split(line, field, "@")
  substed = 0
  len = length(field[1])
  for (i = 2; i < nfields; i++) {
    key = field[i]
    keylen = length(key)
    if (S_is_set[key]) {
      value = S[key]
      line = substr(line, 1, len) "" value "" substr(line, len + keylen + 3)
      len += length(value) + length(field[++i])
      substed = 1
    } else
      len += 1 + keylen
  }

  print line
}

